#!/bin/sh

#ohmyzsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#vim plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then
    # https://github.com/VSCodeVim/Vim#mac
    defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
fi